spring:
  redis:
    database: 0
    host: localhost
    port: 6379

  security:
    user:
      name: user
      password: 123

  jwt:
    secret: secret
    expiration: 7200000
    token: Authorization